import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from 'next/headers';
import ThemeToggle from "./components/ThemeToggle";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme')?.value || 'light';
  const colorTemperature = cookieStore.get('color-temperature')?.value || 'cold';

  return (
    <html lang="en" className={`${theme} ${colorTemperature}`}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeToggle 
          storedTheme={theme as 'dark' | 'light' | null} 
          storedColorTemperature={colorTemperature as 'cold' | 'hot' | null} 
        />
        {children}
      </body>
    </html>
  );
}
